version: '3.8'

services:
  poller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poller
    volumes:
      - /home/desinotorious/mongo/data:/data
      - /home/desinotorious/mongo/log:/var/log/mongodb
    command: [ "supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
    env_file:
      - .env
